### ISSUE TITLE
Joomla 3.7.0 to 3.7.1 update failed with 500 error

### ISSUE THREAD

**Issue by eric13500** [crazy-max/neard#261] opened 2017-05-24 10:35 UTC
Please read this page http://neard.io/doc/reporting-issue before reporting an issue.

Hi!

like in the title: Joomla 3.7.0 to 3.7.1 update failed with 500 error
The previous update went smoothly...

This issue only occur when I try to update directly from the web. 
When I downlowd the package and install from local folder, Joomla go to the panel control and not apply the update...

The logs folder, core/temp folder and 2 screenshots can be downloaded from:
[https://www.sendspace.com/file/ml8i1d](https://www.sendspace.com/file/ml8i1d)

Thanks.

**Comment by crazy-max** [comment] 2017-05-27 16:33
Hi @eric13500,

I keep you in touch

**Comment by N6REJ** [comment] 2017-05-30 20:00
@eric13500 why would you think this is a neard issue?

**Comment by crazy-max** [comment] 2017-05-31 07:12
@eric13500 I cannot reproduce your issue, like @N6REJ said, it's not related to Neard but your application on Joomla. Have you tried to update from 3.7.0 to 3.7.1 from a fresh install ?
I close the issue for the moment, waiting your feedback.
Thanks

**Closed by crazy-max** 2017-05-31 07:12 UTC
